spring:
  # configuration de la datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/border_buddy
    username: postgres
    password: test1234=
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#  # Configuration de l'adresse email envoyant les messages.
#  # Diffère selon les serveurs utilisés. Configuration actuelle pour Gmail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: materialloc.bot@gmail.com
#    password: qllnzgcjybdpjpqv # Test1234=
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

# configuration du chemin de base pour swagger
springdoc:
  swagger-ui:
    path: /swagger

# prop custom pour l'implementation de JWT
app:
  security:
    jwt:
      access-expires-at: 900_000 # 15 min
      refresh-expires-at: 2_592_000_000 # 30 jours
      prefix: "Bearer "
      auth-header: "authorization"
      access-secret: s3cr3t
      refresh-secret: s4cr4t
